### ISSUE TITLE
The minimum samples markers (stars) are missing from the Inferred Response page

### ISSUE THREAD

**Issue by RonanDaly** [marinafloresp/EMERY#1]
When going to
Basket*Cluster interactions -> All interactions -> Inferred response
If the "Mark interactions with a minimum number of samples" slider is put above 0, then no stars show up, even though they show up on the "Number of samples" and "Number of responsive samples" tabs.
![Screenshot 2023-08-09 at 16 27 55](https://github.com/marinafloresp/EMERY/assets/6143277/ec30c4ce-c48f-41e1-be08-b2cef25bbc13)

**Comment by marinafloresp** [comment]
Solved
